# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'OrzBLEDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for OrzBLEDemo
  pod 'OrzBLE', :path => '../../OrzBLE.podspec'
  pod 'RxBluetoothKit', '6.0.0-ios', :source => 'https://github.com/OrzGeeker/Specs.git'

end
